# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#---------------- Felhasználó ----------------
    admin.User:
          class: AppBundle\Admin\Felhasznalo\UserAdmin
          arguments: [~, AppBundle\Entity\Felhasznalo\User, ~]
          tags:
            - { name: sonata.admin, manager_type: orm, group: Felhasználó, label: Felhasználók }

    admin.UserRoleConnect:
          class: AppBundle\Admin\Felhasznalo\UserRoleConnectAdmin
          arguments: [~, AppBundle\Entity\Felhasznalo\UserRoleConnect, ~]
          tags:
            - { name: sonata.admin, manager_type: orm, group: Felhasználó, label: "Felhasználó kapcsolat" }

#---------------- Intezmény ----------------
    admin.Kar:
          class: AppBundle\Admin\Intezmeny\KarAdmin
          arguments: [~, AppBundle\Entity\Intezmeny\Kar, ~]
          tags:
            - { name: sonata.admin, manager_type: orm, group: Intézmény, label: Kar }

    admin.Szak:
          class: AppBundle\Admin\Intezmeny\SzakAdmin
          arguments: [~, AppBundle\Entity\Intezmeny\Szak, ~]
          tags:
            - { name: sonata.admin, manager_type: orm, group: Intézmény, label: Szak }

    admin.Intezet:
          class: AppBundle\Admin\Intezmeny\IntezetAdmin
          arguments: [~, AppBundle\Entity\Intezmeny\Intezet, ~]
          tags:
            - { name: sonata.admin, manager_type: orm, group: Intézmény, label: Intézet }

    admin.Szakirany:
          class: AppBundle\Admin\Intezmeny\SzakiranyAdmin
          arguments: [~, AppBundle\Entity\Intezmeny\Szakirany, ~]
          tags:
            - { name: sonata.admin, manager_type: orm, group: Intézmény, label: Szakirány }
#---------------- Tárgy ----------------
    admin.Targy:
          class: AppBundle\Admin\Targy\TargyAdmin
          arguments: [~, AppBundle\Entity\Intezmeny\Targy, ~]
          tags:
            - { name: sonata.admin, manager_type: orm, group: Tárgy, label: Tárgy }

    admin.TargySorrend:
          class: AppBundle\Admin\Targy\TargySorrendAdmin
          arguments: [~, AppBundle\Entity\Intezmeny\TargySorrend, ~]
          tags:
            - { name: sonata.admin, manager_type: orm, group: Tárgy, label: Tárgyak }

#---------------- Egyéb ----------------
    admin.Hatarido:
          class: AppBundle\Admin\Intezmeny\HataridoAdmin
          arguments: [~, AppBundle\Entity\Intezmeny\Hatarido, ~]
          tags:
            - { name: sonata.admin, manager_type: orm, group: Egyéb, label: Határidő }